name: Github action for terraform validate
run-name: Run terraform validate
on:
  pull_request:
    branches:
      - main
jobs:
  Terraform_Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - run: terraform validate
